name: Java CI
on: [push]
jobs:
  build-and-run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 21
        uses: actions/setup-java@v2
        with:
          java-version: '21'
          distribution: 'temurin'
      - name: Build with Maven
        run: mvn -B package --file pom.xml
      - name: Run program
        run: java -jar target/classes/org/example/Main.jar > output.log
      - name: Upload output log
        uses: actions/upload-artifact@v2
        with:
          name: output-log
          path: output.log